### ISSUE TITLE
How to run JS tests?

### ISSUE THREAD

**Issue by hirrolot** [sergei-romanenko/spsc#2]
I'm not a JS person, so would appreciate some help. I see a file called `test.js` inside `spsc-lite-js`, but I cannot figure out how to launch it:

```
$ node test.js 
/home/hirrolot/Desktop/spsc/spsc-lite-js/test.js:19
	fMain: sll_lang.frule(
	       ^

ReferenceError: sll_lang is not defined
    at Object.<anonymous> (/home/hirrolot/Desktop/spsc/spsc-lite-js/test.js:19:9)
    at Module._compile (node:internal/modules/cjs/loader:1256:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
    at Module.load (node:internal/modules/cjs/loader:1119:32)
    at Module._load (node:internal/modules/cjs/loader:960:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:86:12)
    at node:internal/main/run_main_module:23:47

Node.js v18.18.0
```

**Comment by sergei-romanenko** [comment]
In order to run some example tasks, one has to open `spsc.html` in a browser. And, to run the tests, one has to open `spsc_test.xhtml` in a browser.

Unfortunately, `spsc-lite-js` was made in 2017, and, since than, there have been some changes in html, xml, JavaScript and security rules in browsers, so that something goes wrong. Thus I'll have to look into the matter.

**Comment by sergei-romanenko** [comment]
Now the tests can be run (without using a browser). See README.md.

The problems with running sample tasks are yet to be solved.

**Comment by hirrolot** [comment]
Awesome man, seems that it's working now with no problem. Thanks!

**Comment by sergei-romanenko** [comment]
I reopen the issue, because the problem with running the collection of (interesting) sample tasks is not solved, yet.

(And, the sample tasks are also "tests", in a sense. :-) )

**Comment by sergei-romanenko** [comment]
Now the sample tasks can be run (by means of a local web server). See README.md.

**Comment by hirrolot** [comment]
Works well on my end! By the way, it seems that you've accidentally commited `.vscode/` in the `spsc-lite-js` folder.

**Comment by sergei-romanenko** [comment]
I committed `.vscode/` intentionally. Its contents is useful when using VS Code for dealing with the project, and does no harm when using other IDEs.

**Comment by hirrolot** [comment]
Makes sense, feel free to close this issue, if everything's ok.
