### ISSUE TITLE
A few questions about supercompilation

### ISSUE THREAD

**Issue by hirrolot** [sergei-romanenko/spsc#5]
Thank you for your work on this project. It was really helpful for me to study the actual implementations after reading papers on supercompilation.

I have a few questions on the subject matter (I hope this is an adequate place to ask questions):
 1. Suppose we have a higher-order language. We can write a supercompiler for it directly (as in the project HOSC), or we can perform closure conversion and launch supercompilation on a closure-converted language term. The advantage is that writing a supercompiler for a first-order language is much simpler. Do you see any obstacles of doing so? Have people already experimented with this approach?
 2. Have you seen a project/paper where supercompilation is used for deciding equivalence of terms during dependent type checking?
 3. Where can I find samples of SLL code for stress-testing a supercompiler? In the future, I want to do some profiling of supercompilation and, possibly, find ways to optimize it.

Thanks again and enjoy the New Year!

**Comment by sergei-romanenko** [comment]
I think you'd better discuss the aforementioned questions with Ilya Klyuchnikov, because he has used supercompilation for solving a number of practical problems.

**Comment by hirrolot** [comment]
Closed in favour of https://github.com/ilya-klyuchnikov/sc-mini/issues/13.
