### ISSUE TITLE
Question: comparing subsequences of local configurations (`spsc-lite-js`)

### ISSUE THREAD

**Issue by hirrolot** [sergei-romanenko/spsc#6]
From _"Supercompilation: homeomorphic embedding, call-by-name, partial evaluation"_, I read that 1) trivial configurations are not compared, 2) global configurations are compared only with global ones, and 3) local configurations are compared within the same subsequence of local configurations (e.g., up to the first global configuration). However, in `spsc-lite-js` I cannot really find that local configurations are compared "lexicographically" (see `spsc-lite-js/spsc.js`). Is this simply not implemented or do I miss something? Thanks in advance.

**Comment by sergei-romanenko** [comment]
This code was written by Ilya Klyuchnikov in 2009. It may well be that you've found a deficiency. (And the other readers haven't paid attention to this subtlety.)

**Comment by sergei-romanenko** [comment]
Well. A subtle point is the use of "enhanced homeomorphic embedding".

Enhanced homeomorphic embedding: expressions are compared only if they belong to the same category (as defined by `var_attacked`).

```
function smart_he(exp1, exp2) {
	return var_attacked(exp1) == var_attacked(exp2) &&
		he(exp1, exp2);
}
```

In `spsc-scala` this function is named `strictHE` and is called at two places, as `strictHE(...)` and `!strictHE()`. It seems that it corresponds to testing for "global" and "local" configuration.

But in the "lite" versions of `spsc` there are only "positive" tests for "enhanced homeomorphic". Hence, there is a suspition that the distinction between "global" and "local" configurations is not implemented in the "lite" versions. It can be checked by using a test that is bound to produce different results for supercompilers that make difference between global and local configurations and for those that doesn't.

**Comment by sergei-romanenko** [comment]
It seems that the "lite" versions of `spsc` correspond to the paper:

- Ilya Klyuchnikov and Sergei Romanenko. SPSC: a Simple Supercompiler in Scala. In: _International Workshop on Program Understanding 19-23 June, Altai Mountains, Russia_. Novosibirsk: A.P. Ershov Institute of Informatics Systems, 2009, pages 5-17. [[PDF](https://pat.keldysh.ru/~roman/doc/2009-Klyuchnikov_Romanenko--SPSC-_a_Simple_Supercompiler_in_Scala.pdf)](https://pat.keldysh.ru/~roman/doc/2009-Klyuchnikov_Romanenko--SPSC-_a_Simple_Supercompiler_in_Scala.pdf) [[slides ODP](https://pat.keldysh.ru/~roman/doc/2009-Klyuchnikov_Romanenko--SPSC-_a_Simple_Supercompiler_in_Scala--slides.odp)](https://pat.keldysh.ru/~roman/doc/2009-Klyuchnikov_Romanenko--SPSC-_a_Simple_Supercompiler_in_Scala--slides.odp) [[slides PDF](https://pat.keldysh.ru/~roman/doc/2009-Klyuchnikov_Romanenko--SPSC-_a_Simple_Supercompiler_in_Scala--slides.pdf)](https://pat.keldysh.ru/~roman/doc/2009-Klyuchnikov_Romanenko--SPSC-_a_Simple_Supercompiler_in_Scala--slides.pdf)

This paper doesn't mention the distinction between "global" and "local" control...

**Comment by hirrolot** [comment]
From the paper I see that it refers to the following repository:

 - https://github.com/sergei-romanenko/spsc-idris

and not to this repository, so indeed there might be inconsistencies between the paper and `spsc-lite-js`.

> Hence, there is a suspition that the distinction between "global" and "local" configurations is not implemented in the "lite" versions.

I think that the function `var_attacked` actually returns `true` for global configurations and `false` for local configurations. My question was about a more fine-grained control proposed in the paper, where we stop comparing local configurations after reaching the first global configuration.

**Comment by sergei-romanenko** [comment]
Oh, yes! The two repositories are associated with two different papers!
